---
title: "R Notebook"
output: html_notebook
---
```{r}
#logistic regression

setwd("C:/Users/Deb/Desktop/Tinker/The Analytics Edge/Week 3/Datasets")
quality = read.csv("quality.csv")
str(quality)
summary(quality)
```

```{r}
colors = c("red", "green")
plot(quality$OfficeVisits, quality$Narcotics, col = c("green","red")[quality$PoorCare])
```

```{r}
table(quality$PoorCare)
```

```{r}
#splitting the datset into train and test

#install.packages("caTools")
library(caTools)
set.seed(88)
split = sample.split(quality$PoorCare, SplitRatio = 0.75)
qualityTrain = subset(quality, split == TRUE)
qualityTest = subset(quality, split == FALSE)
```

```{r}
#building a logstic regression model

model1 = glm(PoorCare ~ OfficeVisits + Narcotics, data = qualityTrain, family = binomial)
summary(model1)
```

```{r}
#predicting on training set
predictTrain = predict(model1, type = "response")
summary(predictTrain)
tapply(predictTrain, qualityTrain$PoorCare, mean)
#calculating the confusion matrix
table(qualityTrain$PoorCare, predictTrain > 0.5)
```

```{r}
#Generating ROC curves

#install.packages("ROCR")
library(ROCR)
ROCRpred = prediction(predictTrain, qualityTrain$PoorCare)
ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf)
plot(ROCRperf, colorize = TRUE)
plot(ROCRperf, colorize = TRUE, print.cutoffs.at = seq(0,1,0.1), text.adj = c(-0.2,1.7))
```

```{r}
#Predict on unseen data
predictTest = predict(model1, type = "response", newdata = qualityTest)
ROCRpredTest = prediction(predictTest, qualityTest$PoorCare)
ROCRperf = performance(ROCRpredTest, "tpr", "fpr")
plot(ROCRperf, colorize = TRUE, print.cutoffs.at = seq(0,1,0.1), text.adj = c(-0.2,1.7))
auc = as.numeric(performance(ROCRpredTest, "auc")@y.values)
auc
table(qualityTest$PoorCare, predictTest > 0.3)
```
