---
title: "R Notebook"
output: html_notebook
---
```{r}
setwd("C:/Users/Deb/Desktop/Tinker/The Analytics Edge/Week 2/Datasets")
fluTrain = read.csv("FluTrain.csv")
fluTest = read.csv("FluTest.csv")
summary(fluTrain)
```

```{r}
sort(tapply(fluTrain$Queries, fluTrain$Week, max), decreasing = TRUE)
```

```{r}
hist(fluTrain$ILI)
```

```{r}
plot(fluTrain$Queries, fluTrain$ILI)
```

```{r}
plot(fluTrain$Queries, log(fluTrain$ILI))
```
```{r}
#linear regression model

model1 = lm(log(ILI) ~ Queries, data = fluTrain)
summary(model1)
```

```{r}
cor(fluTrain$ILI, fluTrain$Queries)
exp(-0.5*0.814)
```

```{r}
#predicting on unseen data
predTest1 = exp(predict(model1, newdata = fluTest))
predTest1
fluTest$ILI
```

```{r}
#calculating the RMSE
SSE = sum((fluTest$ILI-predTest1)^2)
RMSE = sqrt(SSE/nrow(fluTest))
RMSE
```

```{r}
#time series analysis
library(zoo)
ILILag2 = lag(zoo(fluTrain$ILI), -2, na.pad = TRUE)
fluTrain$ILILag2 = coredata(ILILag2)
summary(fluTrain$ILILag2)
```

```{r}
#plotting the relationship between ILILag2 and ILI
plot(fluTrain$ILILag2,log(fluTrain$ILI))
```

```{r}
#training a time series model

model2 = lm(log(ILI)~ Queries + log(ILILag2), data = fluTrain)
summary(model2)
```

```{r}
ILILag2 = lag(zoo(fluTest$ILI), -2, na.pad = TRUE)
fluTest$ILILag2 = coredata(ILILag2)

#filling in the missing data in the fluTest dataset
fluTest$ILILag2[1] = fluTrain$ILI[nrow(fluTrain)-1]
fluTest$ILILag2[2] = fluTrain$ILI[nrow(fluTrain)]
summary(fluTest$ILILag2)

fluTest$ILILag2[1]
fluTest$ILILag2[2]
```
```{r}
#predicting on unseen data
predictTimeSeries = exp(predict(model2, newdata = fluTest))
SSEmodel2 = sum((fluTest$ILI - predictTimeSeries)^2)
RMSEmodel2 = sqrt(SSEmodel2/nrow(fluTest))
RMSEmodel2
```

